apt_packages_list:
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - git
  - ubuntu-restricted-extras
  - ubuntu-restricted-addons
  - geany
  - meld
  - wget
  - fonts-firacode
  - fonts-powerline
  - fonts-jetbrains-mono
  - gnome-tweaks
  - vlc
  - gimp
  - inkscape
  - gparted
  - stacer
  - cpu-x
  - htop
  - terminator
  - zsh
  - unzip
  - build-essential
  - vim
sdkman_java_versions:
  - 7.0.352-zulu
  - 8.0.492-zulu
  - 11.0.31-zulu
  - 17.0.19-zulu
  - 21.0.11-zulu
  - 25.0.3-zulu
sdkman_default_java: 25.0.3-zulu
sdkman_maven_versions:
  - 3.6.3
  - 3.9.15
maven_default_version: 3.9.15
nvm_node_versions:
  - v8.17.0
  - v10.24.1
  - v12.22.12
  - v14.21.3
  - v16.20.1
  - v18.20.8
  - v20.22.2
  - v24.15.0
  - lts/*
  - node
node_default_version: v24.14.0
vscode_extensions:
  - amazonwebservices.amazon-q-vscode
  - EditorConfig.EditorConfig
  - dbaeumer.vscode-eslint
  - vscjava.vscode-java-pack
  - mhutchie.git-graph
  - donjayamanne.githistory
  - eamodio.gitlens
  - yzane.markdown-pdf
  - PKief.material-icon-theme
  - rocketseat.theme-omni
  - esbenp.prettier-vscode
  - humao.rest-client
  - SonarSource.sonarlint-vscode
  - vscjava.vscode-spring-boot-dashboard
  - bradlc.vscode-tailwindcss
  - Vue.volar
  - redhat.vscode-xml
  - redhat.vscode-yaml
beekeeper_studio: 5.6.5
keystore_explorer: 5.6.1
nvm: v0.40.4
user: richard
meslo_font_url_base: https://github.com/romkatv/powerlevel10k-media/raw/master
meslo_font_dest_dir: /home/richard/.local/share/fonts
meslo_font_files:
  - "MesloLGS NF Regular.ttf"
  - "MesloLGS NF Bold.ttf"
  - "MesloLGS NF Italic.ttf"
  - "MesloLGS NF Bold Italic.ttf"
home_dir: /home/richard
git_name: Richard Mendes Madureira
git_email: richard.madureira@dataprev.gov.br

intellij_idea_version: 2026.1.1
terminal_font: MesloLGS NF Regular 16

favorite_apps_desejados:
  - org.gnome.Nautilus.desktop
  - org.gnome.Ptyxis.desktop
  - terminator.desktop
  - firefox_firefox.desktop
  - google-chrome.desktop
  - microsoft-edge.desktop
  - brave-browser.desktop
  - code.desktop
  - idea.desktop
  - beekeeper-studio.desktop
  - dbeaver-ce.desktop
  - org.gnome.Meld.desktop
  - geany.desktop
  - kse.desktop

vpn_command: >
    sudo valgrind openconnect -b -q portalvpncert.dataprev.gov.br
    --certificate="pkcs11:model=ePass2003;manufacturer=EnterSafe%00;serial=307B3B228058001F;token=SOLUTI;id=%09%0E%0A%69%00%00%00%00;object=RICHARD%20MENDES%20MADUREIRA%3A03930263610;type=cert"
    --protocol=gp
    -u richard.madureira@dataprev.gov.br
    --servercert pin-sha256:XU0rZPEnB8GhPG+sd//CbY7PAayc4N0khTwqTVzzm/Y=
    --authgroup=GW_EXT_DCDF_A3
    --disable-ipv6
    --no-dtls

vpn_script_path: /usr/local/bin/vpn
