- name: Verificar se SDKMAN já está instalado
  stat:
    path: "{{home_dir}}/.sdkman"
  register: sdkman_dir
  become_user: "{{ user }}"

- name: Instalar SDKMAN
  become_user: "{{ user }}"
  shell: curl -s "https://get.sdkman.io" | bash
  when: not sdkman_dir.stat.exists

- name: Garantir que o sdkman_auto_answer está definido como true
  ansible.builtin.lineinfile:
    path: "{{ home_dir }}/.sdkman/etc/config"
    regexp: '^sdkman_auto_answer='
    line: 'sdkman_auto_answer=true'
    create: yes
    state: present