- name: Configurar Desktop Ubuntu 26.04
  hosts: all
  become: false
  become_method: sudo
  become_flags: ""
  roles:
    - common # ok
    - apt_packages # ok
    - zsh # ok
    - fonts # ok
    - powerlevel10k # ok
    - browsers # ok
    - vscode # ok
    - beekeeper # ok
    - keystore-explorer # ok
    - sdkman # ok
    - nvm # ok
    - spotify # ok
    - docker # ok
    - gitconfig # ok
    - gsettings
    # - token-a3
    - intellij-idea
    