- name: Configurar Desktop Ubuntu 26.04
  hosts: all
  become: false
  become_method: sudo
  become_flags: ""
  roles:
    - common
    - apt_packages
    - zsh
    - fonts
    - powerlevel10k
    - browsers
    - vscode
    - beekeeper
    - dbeaver
    - keystore-explorer
    - sdkman
    - nvm
    - spotify
    - docker
    - gitconfig
    - token-a3
    - intellij-idea
    - gsettings
    