---
- name: Preparação da Estação de Trabalho
  hosts: localhost
  connection: local
  tasks:

    - name: Atualizando Sistema Operacional
      become: true
      apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes
        install_recommends: yes
        autoremove: yes


