---
- name: Preparação da Estação de Trabalho
  hosts: localhost
  connection: local
  tasks:

    - name: Atualizando Sistema Operacional
      become: true
      apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes
        install_recommends: yes
        autoremove: yes

    - name: Instalando aplicações que estão nos repositórios padrões do Ubuntu
      become: true
      apt:
        name: '{{ item }}'
        install_recommends: yes
        state: present
      loop:
        - software-properties-common
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - git
        - ubuntu-restricted-extras
        - ubuntu-restricted-addons
        - geany
        - meld
        - wget
        - fonts-firacode
        - fonts-powerline
        - fonts-jetbrains-mono
        - gnome-tweaks
        - vlc
        - gimp
        - inkscape
        - ttf-mscorefonts-installer
        - gparted
        - stacer
        - blender
        - filezilla
        - cpu-x
        - htop
        - terminator
        - tilix
        - openconnect
        - zsh

    - block:
      - name: Criação do arquivo .zshrc
        template:
          src: './resources/zsh/zshrc.template'
          dest: '/home/{{ ansible_user_id }}/.zshrc'
          mode: 0755

      - name: Verificação se Oh-My-zsh está instalado
        command: test -d /home/{{ ansible_user_id }}/.oh-my-zsh
        register: ohmyzsh
        ignore_errors: true

      - name: Instalação do Oh-My-zsh
        shell:
          cmd: 'curl -fsL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash'
          warn: false
        when: ohmyzsh.rc != 0

      - name: Alteração do shell default para ZSH
        become: yes
        user:
          name: '{{ ansible_user_id }}'
          shell: /bin/zsh

      - name: Configuração de AutoSuggestions
        git:
          repo: 'https://github.com/zsh-users/zsh-autosuggestions'
          dest: '/home/{{ ansible_user_id }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions'

      - name: Configuração de variavel ambiente para o OH-MY-ZSH
        lineinfile:
          path: /home/{{ ansible_user_id }}/.zshrc
          line: 'export ZSH=/home/richard/.oh-my-zsh'
          insertafter: '# Set up the prompt'
      - name: Inclusão da importação do oh-my-zsh
        lineinfile:
          path: /home/{{ ansible_user_id }}/.zshrc
          line: 'source $ZSH/oh-my-zsh.sh'
          insertafter: EOF

    - name: Criação dos diretórios necessários
      become: true
      file:
        path: '{{ item }}'
        state: directory
        mode: 0777
        group: '{{ ansible_user_id }}'
        seuser: '{{ ansible_user_id }}'
      loop:
        - '/opt/programas'
        - '/dtp'
        - '/home/{{ ansible_user_id }}/.m2'
        - '/home/{{ ansible_user_id }}/.local/share/fonts'

    - block:
      - name: Instalação do Firefox Developer Edition
        unarchive:
          src: 'https://download-installer.cdn.mozilla.net/pub/devedition/releases/126.0b5/linux-x86_64/en-US/firefox-126.0b5.tar.bz2'
          dest: '/opt/programas'
          remote_src: yes
          creates: '/opt/programas/firefox'

      - name: Criação do arquivo settings.xml e toolchains.xml
        template:
          src: './resources/apache-maven/settings.xml'
          dest: '/home/{{ ansible_user_id }}/.m2/settings.xml'

      - name: Criacao do arquivo toolchains.xml
        template:
          src: './resources/apache-maven/toolchains.xml'
          dest: '/home/{{ ansible_user_id }}/.m2/toolchains.xml'
        loop:
          - { content: './resources/apache-maven/settings.xml', dest: '/home/{{ ansible_user_id }}/.m2/settings.xml'}
          - { content: './resources/apache-maven/toolchains.xml', dest: '/home/{{ ansible_user_id }}/.m2/toolchains.xml'}

    - name: Instalação do Keystore Explorer
      become: true
      apt:
        deb: 'https://github.com/kaikramer/keystore-explorer/releases/download/v5.5.1/kse_5.5.1_all.deb'

    - name: Configuração do git (.gitconfig)
      git_config:
        scope: global
        name: '{{ item.name }}'
        value: '{{ item.value }}'
      loop:
        - { name: 'user.name', value: 'Richard Mendes Madureira' }
        - { name: 'user.email', value: 'richard.madureira@dataprev.gov.br' }
        - { name: 'http.sslVerify', value: 'false' }
        - { name: 'credential.helper', value:  'cache --timeout=36000' }
        - { name: 'core.editor', value:  'code --wait --new-window' }
        - { name: 'diff.tool', value: 'vscode' }
        - { name: 'difftool.vscode.cmd', value: 'code --wait --diff $LOCAL $REMOTE' }
        - { name: 'difftool.prompt', value: 'false' }
        - { name: 'merge.tool', value: 'vscode' }
        - { name: 'mergetool.vscode.cmd', value: 'code --wait $MERGED' }

    - block:
      - name: Instalação da chave PGP do Google Chrome
        become: true
        apt_key:
          url: 'https://dl.google.com/linux/linux_signing_key.pub'
          state: present

      - name: Instalação do repositório do Google Chrome
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
          state: present
          filename: google-chrome

      - name: Instalação do Google Chrome Stable
        become: true
        apt:
          name: google-chrome-stable
          state: latest
          update_cache: yes

    - block:
      - name: Instalação da chave PGP do Docker
        become: true
        apt_key:
          url: 'https://download.docker.com/linux/ubuntu/gpg'
          state: present

      - name: Instalação do repositório do docker
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
          state: present
          filename: docker-ce

      - name: Instalação do Docker
        become: true
        apt:
          name: '{{ item }}'
          install_recommends: yes
        loop:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

      - name: Inclusão de usuário existente no grupo docker
        become: yes
        user:
          name: '{{ ansible_user_id }}'
          groups: docker
          append: yes

    - block:
      - name: Instalação da chave PGP da Microsoft
        become: true
        apt_key:
          url: 'https://packages.microsoft.com/keys/microsoft.asc'
          state: present

      - name: Instalação do repositório do Visual Studio Code
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/code stable main'
          state: present
          filename: vscode

      - name: Instalação do repositório do Microsoft Edge
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main'
          state: present
          filename: microsoft-edge

      - name: Instalação do Visual Studio Code, Microsoft Teams e Microsoft Edge Stable
        become: true
        apt:
          name: '{{ item }}'
        loop:
          - code
          - microsoft-edge-stable

      - name: Verificar se as extensões do Visual Studio Code estão instaladas
        shell: code --list-extensions
        register: vscode_extensions

      - name: Instalação das extensões para o Visual Studio Code
        shell:
          cmd: code --install-extension '{{ item }}' --force
        loop:
          - dbaeumer.vscode-eslint
          - Dart-Code.flutter
          - Dart-Code.dart-code
          - donjayamanne.githistory
          - eamodio.gitlens
          - GitHub.copilot
          - PKief.material-icon-theme
          - ms-edgedevtools.vscode-edge-devtools
          - vscjava.vscode-spring-boot-dashboard
          - rangav.vscode-thunder-client
          - vscjava.vscode-java-pack
          - rocketseat.theme-omni
          - redhat.java
        when: item not in vscode_extensions.stdout_lines

    - name: Instalação do Spotify
      become: true
      snap:
        name: spotify
        classic: yes

    - name: Inclusão de fontes para o PowerLevel10K
      get_url: url={{ item }} dest=/home/{{ ansible_user_id }}/.local/share/fonts
      loop:
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
      

    - name: Inclusão de fontes
      copy:
        src: '{{ item }}'
        dest: '/home/{{ ansible_user_id }}/.local/share/fonts'
      loop:
        - './resources/fonts/MesloLGS NF Bold Italic.ttf'
        - './resources/fonts/MesloLGS NF Bold.ttf'
        - './resources/fonts/MesloLGS NF Italic.ttf'
        - './resources/fonts/MesloLGS NF Regular.ttf'

    - name: "nvm"
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}"
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    - name: "node"
      shell: >
        . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }}
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}"
        creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ item }}"
      loop:
        - v8.17.0
        - v10.24.21
        - v12.22.12
        - v20.12.2
