---
- name: Preparação da Estação de Trabalho
  hosts: localhost
  connection: local
  vars:
    maven_settings: |
      <?xml version="1.0" encoding="utf-8"?>
      <settings>
        <mirrors>
          <mirror>
            <id>mirror-dataprev</id>
            <name>Maven Public Dtaprev</name>
            <url>http://www-bin.prevnet/repository/public/</url>
            <mirrorOf>*</mirrorOf>
          </mirror>
          <mirror>
            <id>nexus</id>
            <mirrorOf>nexus</mirrorOf>
            <url>http://internal/nexus/content/repositories/thirdparty</url>
          </mirror>
          <mirror>
            <id>google</id>
            <mirrorOf>google</mirrorOf>
            <url>http://google-maven-repository.googlecode.com/svn/repository</url>
          </mirror>
        </mirrors>
      </settings>
    maven_toolchains: |
      <?xml version="1.0" encoding="UTF8"?>
      <toolchains>
        <toolchain>
          <type>jdk</type>
          <provides>
            <version>1.8</version>
            <vendor>openjdk</vendor>
          </provides>
          <configuration>
            <jdkHome>/opt/programas/jdk1.8.0_131/</jdkHome>
          </configuration>
        </toolchain>
        <toolchain>
          <type>jdk</type>
          <provides>
            <version>11</version>
            <vendor>openjdk</vendor>
          </provides>
          <configuration>
            <jdkHome>/usr/lib/jvm/java-11-openjdk-amd64/</jdkHome>
          </configuration>
        </toolchain>
        <toolchain>
          <type>jdk</type>
          <provides>
            <version>17</version>
            <vendor>oracle</vendor>
          </provides>
          <configuration>
            <jdkHome>/usr/lib/jvm/jdk-17</jdkHome>
          </configuration>
        </toolchain>
      </toolchains>
  tasks:

    - name: Atualizando Sistema Operacional
      become: true
      apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes
        install_recommends: yes
        autoremove: yes

    - name: Instalando aplicações que estão nos repositórios padrões do Ubuntu
      become: true
      apt:
        name: '{{ item }}'
        install_recommends: yes
        state: present
      loop:
        - software-properties-common
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - git
        - openjdk-11-jdk
        - ubuntu-restricted-extras
        - ubuntu-restricted-addons
        - geany
        - meld
        - wget
        - fonts-firacode
        - fonts-powerline
        - fonts-font-awesome
        - gnome-tweaks
        - vlc
        - gimp
        - inkscape
        - ttf-mscorefonts-installer
        - gparted
        - stacer
        - blender
        - filezilla
        - cpu-x
        - htop
        - terminator
        - openconnect
        - network-manager-openconnect
        - network-manager-openconnect-gnome
        - libglu1-mesa
        - clang
        - cmake
        - ninja-build
        - pkg-config
        - libgtk-3-dev
        - liblzma-dev
        - zsh
        - krita

    - name: Criação dos diretórios necessários
      become: true
      file:
        path: '{{ item }}'
        state: directory
        mode: 0777
        group: richard
        seuser: richard
      loop:
        - '/opt/programas' 
        - '/dtp'
        - '/home/richard/.m2'

    - block:
      - name: Instalação do Eclipse Java EE
        unarchive:
          src: 'https://eclipse.c3sl.ufpr.br/technology/epp/downloads/release/2022-03/R/eclipse-jee-2022-03-R-linux-gtk-x86_64.tar.gz'
          dest: /opt/programas
          remote_src: yes
          creates: /opt/programas/eclipse
      - name: Alteração das configurações de memória do Eclipse (eclipse.ini)
        lineinfile:
          dest: /opt/programas/eclipse/eclipse.ini
          regexp: '{{ item.regexp }}'
          line: '{{ item.line }}'
          state: present
        loop:
          - { regexp: '^-Xms', line: '-Xms512m' }
          - { regexp: '^-Xmx', line: '-Xmx4096m' }

    - block:
      - name: Instalação do Apache Maven
        unarchive:
          src: 'https://dlcdn.apache.org/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz'
          dest: '/opt/programas'
          remote_src: yes
          creates: '/opt/programas/apache-maven-3.8.5'

      - name: Criação do arquivo settings.xml
        copy:
          content: '{{ item.content }}'
          dest: '{{ item.dest }}'
        loop:
          - { content: '{{ maven_settings }}', dest: '/home/richard/.m2/settings.xml'}
          - { content: '{{ maven_toolchains }}', dest: '/home/richard/.m2/toolchains.xml'}

      - name: Configuração de variáveis ambientes
        lineinfile:
          dest: /home/richard/.zshrc
          line: '{{ item.line }}'
          regexp: '{{ item.regexp }}'
          insertafter: 'EOF'
          state: present
        loop:
          - { regexp: '^export MAVEN_HOME', line: 'export MAVEN_HOME="/opt/programas/apache-maven-3.8.5"' }
          - { regexp: '^export PATH', line: 'export PATH="$PATH:$MAVEN_HOME/bin"' }

      - name: Instalação do Keystore Explorer
        apt:
          deb: 'https://github.com/kaikramer/keystore-explorer/releases/download/v5.5.1/kse_5.5.1_all.deb'

      - name: Configuração do git (.gitconfig)
        git_config:
          scope: global
          name: '{{ item.name }}'
          value: '{{ item.value }}'
        loop:
          - { name: 'user.name', value: 'Richard Mendes Madureira' }
          - { name: 'user.email', value: 'richard.madureira@dataprev.gov.br' }
          - { name: 'http.sslVerify', value: 'false' }
          - { name: 'credential.helper', value:  'cache --timeout=36000' }
          - { name: 'core.editor', value:  'code --wait --new-window' }
          - { name: 'diff.tool', value: 'vscode' }
          - { name: 'difftool.vscode.cmd', value: 'code --wait --diff $LOCAL $REMOTE' }
          - { name: 'difftool.prompt', value: 'false' }
          - { name: 'merge.tool', value: 'vscode' }
          - { name: 'mergetool.vscode.cmd', value: 'code --wait $MERGED' }
      
    - block:
      - name: Instalação da chave PGP do Google Chrome
        become: true
        apt_key:
          url: 'https://dl.google.com/linux/linux_signing_key.pub'
          state: present
      - name: Instalação do repositório do Google Chrome
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
          state: present
          filename: google-chrome
      - name: Instalação do Google Chrome Stable
        become: true
        apt:
          name: google-chrome-stable
          state: latest
          update_cache: yes
    
    - block:
      - name: Instalação da chave PGP do Docker
        become: true
        apt_key:
          url: 'https://download.docker.com/linux/ubuntu/gpg'
          state: present
      - name: Instalação do repositório do docker
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
          state: present
          filename: docker-ce
      - name: Instalação do Docker
        become: true
        apt:
          name: '{{ item }}'
          install_recommends: yes
        loop:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      - name: Inclusão de usuário existente no grupo docker
        become: yes
        user: 
          name: '{{ ansible_user_id }}'
          groups: docker
          append: yes
      - name: Instalação do Docker Compose
        become: true
        get_url:
          url: 'https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64'
          dest: '/usr/local/bin/docker-compose'
          mode: 755
      - name: Instalação do Docker Machine Bash Completion
        become: true
        get_url:
          url: 'https://raw.githubusercontent.com/docker/machine/v0.16.2/contrib/completion/bash/docker-machine.bash'
          dest: '/etc/bash_completion.d/docker-machine'
      - name: Instalação do Docker-Compose Bash Completion
        become: true
        get_url:
          url: 'https://raw.githubusercontent.com/docker/compose/1.29.2/contrib/completion/bash/docker-compose'
          dest: '/etc/bash_completion.d/docker-compose'
      - name: Instalação do Docker-Compose e Docker Machine no Zsh Completion
        lineinfile:
          path: /home/{{ ansible_user_id }}/.zshrc
          regexp: '^plugins='
          line: 'plugins=(git docker docker-compose mvn nvm npm yarn zsh-autosuggestions)'

    - block:
      - name: Instalação da chave PGP da Microsoft
        become: true
        apt_key:
          url: 'https://packages.microsoft.com/keys/microsoft.asc'
          state: present
      - name: Instalação do repositório do Visual Studio Code
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/code stable main'
          state: present
          filename: vscode
      - name: Instalação do repositório do Microsoft Teams
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main'
          state: present
          filename: teams
      - name: Instalação do repositório do Microsoft Edge
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main'
          state: present
          filename: microsoft-edge
      - name: Instalação do Visual Studio Code, Microsoft Teams e Microsoft Edge Stable
        become: true
        apt:
          name: code
        loop:
          - code
          - teams
          - microsoft-edge-stable
      - name: Instalação das extensões para o Visual Studio Code
        shell:
          cmd: code --install-extension '{{ item }}'
        loop: 
          - dbaeumer.vscode-eslint
          - Dart-Code.flutter
          - Dart-Code.dart-code
          - ms-azuretools.vscode-docker
          - donjayamanne.githistory
          - eamodio.gitlens
          - GitHub.copilot
          - GabrielBB.vscode-lombok
          - PKief.material-icon-theme
          - ms-edgedevtools.vscode-edge-devtools
          - vscjava.vscode-spring-boot-dashboard
          - rangav.vscode-thunder-client
          - vscjava.vscode-java-pack
          - rocketseat.theme-omni

    - block:
      - name: Verificação se  Oh-My-zsh está instalado
        command: test -d /home/{{ ansible_user_id }}/.oh-my-zsh
        register: ohmyzsh
        ignore_errors: true
      - name: Instalando Oh-My-zsh
        shell:
          cmd: 'curl -fsL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash'
          warn: false
        when: ohmyzsh.rc != 0
      - name: Alterando o Default shell para  ZSH
        become: yes
        user:
          name: '{{ ansible_user_id }}'
          shell: /bin/zsh
      - name: Changing Default ZSH Theme to Agnoster
        lineinfile:
          path: /home/{{ ansible_user_id }}/.zshrc
          regexp: '^ZSH_THEME='
          line: 'ZSH_THEME="agnoster"'
      - name: Criação do diretório ZSH Completion
        file:
          path: /home/{{ ansible_user_id }}/.oh-my-zsh/completions
          state: directory
          mode: 0755
      - name: Adicionando autoload ao compinit
        lineinfile:
          path: /home/{{ ansible_user_id }}/.zshrc
          line: 'autoload -U compinit && compinit'
          state: present
      - name: Configuração de AutoSuggestions
        git:
          repo: 'https://github.com/zsh-users/zsh-autosuggestions'
          dest: '/home/richard/.oh-my-zsh/custom/plugins/zsh-autosuggestions'


    - block:
      - name: Instalação do Spotify
        snap:
          name: spotify
          classic: yes
          
    - block:
      - name: Personalização do sistema operacional
        dconf:
          key: '{{item.key}}'
          value: '{{item.value}}'
          state: present
        loop:
          - { key: '/org/gnome/desktop/interface/gtk-theme', value: "'Yaru-olive-dark'"}
          - { key: '/org/gnome/shell/extensions/ding icon-size', value: "'small'"}
          - { key: '/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size', value: '32'}
          - { key: '/org/gnome/shell/extensions/dash-to-dock/dock-position', value: "'BOTTOM'"}
          - { key: '/org/gnome/shell/extensions/dash-to-dock/extend-height', value: 'false'}
          - { key: '/org/gnome/shell/extensions/dash-to-dockd/dock-fixed', value: 'false'}
          - { key: '/org/gnome/shell/extensions/dash-to-dock/multi-monitor', value: 'true'}
          #- { key: '/org/gnome/shell/favorite-apps', value: "['ubuntu-desktop-installer_ubuntu-desktop-installer.desktop', 'ubiquity.desktop', 'firefox_firefox.desktop', 'thunderbird.desktop', 'org.gnome.Nautilus.desktop', 'rhythmbox.desktop', 'libreoffice-writer.desktop', 'snap-store_ubuntu-software.desktop', 'yelp.desktop']"}
          - { key: '/org/gnome/shell/favorite-apps', value: "['org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'google-chrome.desktop', 'firefox.desktop', 'microsoft-edge-dev.desktop', 'microsoft-edge.desktop', 'firefox-developer-edition.desktop', 'code.desktop', 'eclipse.desktop', 'postman.desktop', 'dbeaver-ce_dbeaver-ce.desktop', 'spotify.desktop']"}
