all:
  hosts:
    localhost:
      ansible_connection: local
      become_user: richard

    dev-desktop:
      ansible_host: 192.168.100.67
      ansible_user: richard
      ansible_become: true
      ansible_become_method: sudo
      ansible_become_ask_pass: true