all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_user: richard
      ansible_become: true

  children:
    dev-desktop:
      vars:
        ansible_user: richard
        ansible_become: true
        ansible_become_method: sudo
        ansible_become_ask_pass: true
      hosts:
        eniac:
          ansible_host: 192.168.100.5
        eniac-note:
          ansible_host: 192.168.100.67
        eniac-2:
          ansible_host: 192.168.100.52
