- name: clock-show-weekday - Verificar se a propriedade clock-show-weekday está com o valor padrão
  become_user: "{{ user }}"
  ansible.builtin.command: dconf read /org/gnome/desktop/interface/clock-show-seconds
  register: clock_show_weekday_default
  changed_when: false

- name: clock-show-weekday - Verificar se dia da semana está sendo exibido
  become_user: "{{ user }}"
  ansible.builtin.command: >
    gsettings get org.gnome.desktop.interface clock-show-weekday
  register: show_weekday
  changed_when: false

- name: clock-show-weekday - Habilitar exibição de dia da semana
  become_user: "{{ user }}"
  ansible.builtin.command: >
    gsettings set org.gnome.desktop.interface clock-show-weekday true
  when: show_weekday.stdout != "true" or clock_show_weekday_default.stdout == ""