- name: Verificar tamanho atual dos ícones do dock
  become_user: "{{ user }}"
  ansible.builtin.command: >
    gsettings get org.gnome.shell.extensions.dash-to-dock dash-max-icon-size
  register: dock_icon_size
  changed_when: false

- name: Ajustar tamanho dos ícones do dock
  become_user: "{{ user }}"
  ansible.builtin.command: >
    gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 40
  when: dock_icon_size.stdout != "40"