- import_tasks: accent-color.yml
- import_tasks: clock-show-seconds.yml
- import_tasks: clock-show-weekday.yml
- import_tasks: color-scheme.yml
- import_tasks: dash-max-icon-size.yml
- import_tasks: dock-fixed.yml
- import_tasks: dock-position.yml
- import_tasks: extend-height.yml
- import_tasks: favorite-apps.yml
- import_tasks: font-name.yml
- import_tasks: multi-monitor.yml
- import_tasks: use-font-system.yml