- name: Instalar Zsh
  apt:
    name: zsh
    state: present

- name: Verificar se Oh My Zsh já está instalado
  stat:
    path: "{{ home_dir }}/.oh-my-zsh"
  register: ohmyzsh_dir

- name: Instalar Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  become_user: "{{ user }}"
  when: not ohmyzsh_dir.stat.exists

- name: Verificar se zsh-autosuggestions já está instalado
  stat:
    path: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  register: zsh_autosuggestions

- name: Instalar zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  become_user: "{{ user }}"
  when: not zsh_autosuggestions.stat.exists

- name: Habilitar plugins no .zshrc
  lineinfile:
    path: "{{ home_dir }}/.zshrc"
    regexp: '^plugins='
    line: 'plugins=(git zsh-autosuggestions)'
  become_user: "{{ user }}"

- name: Definir Zsh como shell padrão
  user:
    name: "{{ user }}"
    shell: /usr/bin/zsh
