- name: Configuração do git (.gitconfig)
  become: true
  become_user: "{{ user }}"
  git_config:
    scope: global
    name: '{{ item.name }}'
    value: '{{ item.value }}'
  loop:
    - { name: 'user.name', value: '{{ git_name }}' }
    - { name: 'user.email', value: '{{ git_email }}' }
    - { name: 'http.sslVerify', value: 'false' }
    - { name: 'credential.helper', value:  'cache --timeout=36000' }
    - { name: 'core.editor', value:  'code --wait --new-window' }
    - { name: 'diff.tool', value: 'vscode' }
    - { name: 'difftool.vscode.cmd', value: 'code --wait --diff $LOCAL $REMOTE' }
    - { name: 'difftool.prompt', value: 'false' }
    - { name: 'merge.tool', value: 'vscode' }
    - { name: 'mergetool.vscode.cmd', value: 'code --wait $MERGED' }