- name: Garantir que o diretório de fontes do usuário existe
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: "{{ meslo_font_dest_dir }}"
    state: directory
    mode: '0755'

- name: Verificar se as fontes MesloLGS NF já estão instaladas
  become: true
  become_user: "{{ user }}"
  ansible.builtin.stat:
    path: "{{ meslo_font_dest_dir }}/{{ item }}"
  register: font_check
  loop: "{{ meslo_font_files }}"

- name: Baixar as fontes MesloLGS NF (apenas se não existirem)
  become: true
  become_user: "{{ user }}"
  ansible.builtin.get_url:
    url: "{{ meslo_font_url_base }}/{{ item.item | replace(' ', '%20') }}"
    dest: "{{ meslo_font_dest_dir }}/{{ item.item }}"
    mode: '0644'
  loop: "{{ font_check.results }}"
  when: not item.stat.exists
  register: download_fonts

- name: Atualizar o cache de fontes do sistema
  become: true
  become_user: "{{ user }}"
  ansible.builtin.command: fc-cache -fv
  when: download_fonts.changed
  changed_when: true